module.exports = {
  HtmlWebpackPlugin: [{
    filename: 'index.html',
    template: '_shared/layout.ejs',
    includeName: 'index.ejs',
    headerID: 'headerIdx',
    description: '',
    chunks: ['index']
  }, {
    filename: 'University/Web/enUS/index.html',
    template: '_shared/layout.ejs',
    includeName: 'index.ejs',
    headerID: 'headerIdx',
    description: '',
    chunks: ['index']
  }, {
    filename: 'University/Prospectivestudents/zhTW/index.html',
    template: '_shared/layout.ejs',
    includeName: 'index.ejs',
    headerID: 'headerIdx',
    description: '',
    chunks: ['index']
  }, {
    filename: 'University/Prospectivestudents/enUS/index.html',
    template: '_shared/layout.ejs',
    includeName: 'index.ejs',
    headerID: 'headerIdx',
    description: '',
    chunks: ['index']
  }, {
    filename: 'University/Alumni/zhTW/index.html',
    template: '_shared/layout.ejs',
    includeName: 'index.ejs',
    headerID: 'headerIdx',
    description: '',
    chunks: ['index']
  }, {
    filename: 'University/Alumni/enUS/index.html',
    template: '_shared/layout.ejs',
    includeName: 'index.ejs',
    headerID: 'headerIdx',
    description: '',
    chunks: ['index']
  }]
};
